{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  labels:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.blueHost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "helm-guestbook.fullname" . }}
              servicePort: 80
    - host: {{ .Values.greenHost }}
      http: 
        paths:
          - path: /
            backend:
               serviceName: {{ template "helm-guestbook.fullname" . }}-preview
               servicePort: 80
  {{- end }}
