apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "guestbook.fullname" . }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  source:
    path: charts/
    repoURL: 'https://github.com/psiservices-sabbas/sample-nginx-helm.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-{{ .Values.env }}.yaml
      parameters:
        - name: image.tag
          value: {{ .Values.image.tag }}		  
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
